[package]
name = "rustsdl2"
version = "0.1.0"
authors = ["Bernd Riedl <bernd.riedl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.34"
features = ["bundled", "static-link"]
